title: "Aditya"
author: "Aditya"
description: 'Made with <b style="color: #f45;">&lt;3</b>'
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: false # show article excerpts on the home page
show_frame: false # adds a gray frame to the site
show_sidebar: false # show a sidebar instead of the usual header
minimal: true # use a dark header

# Menu

navigation: # accepts {file, title, url, icon, sidebaricon}
  # - { file: "index.md", title: "Homepage" }
  # - { file: "blog.md", title: "Blog" }
  - { title: Mail, icon: envelope, url: "mailto:neelaadityakumar@gmail.com" }
  - { title: Github, icon: github, url: "https://github.com/neelaadityakumar" }
  - {
      title: Linkedin,
      icon: linkedin,
      url: "https://www.linkedin.com/in/aditya-kumar-994aa6155/",
    }

  - { url: "/ADITYA-KUMAR-RESUME.pdf", title: "CV" }
external: # shows a footer with social links - for available icons see fontawesome.com/icons
  - {
      title: Subscribe,
      icon: medium-m,
      url: "https://medium.com/@neelaadityakumar",
    }

comments:

plugins:
  - jekyll-feed
